// Code generated by build/gen-codes. DO NOT EDIT.

package evdev

// ABS
const (
	ABS_BRAKE          = 0x0a
	ABS_CNT            = (ABS_MAX + 1)
	ABS_DISTANCE       = 0x19
	ABS_GAS            = 0x09
	ABS_HAT0X          = 0x10
	ABS_HAT0Y          = 0x11
	ABS_HAT1X          = 0x12
	ABS_HAT1Y          = 0x13
	ABS_HAT2X          = 0x14
	ABS_HAT2Y          = 0x15
	ABS_HAT3X          = 0x16
	ABS_HAT3Y          = 0x17
	ABS_MAX            = 0x3f
	ABS_MISC           = 0x28
	ABS_MT_BLOB_ID     = 0x38
	ABS_MT_DISTANCE    = 0x3b
	ABS_MT_ORIENTATION = 0x34
	ABS_MT_POSITION_X  = 0x35
	ABS_MT_POSITION_Y  = 0x36
	ABS_MT_PRESSURE    = 0x3a
	ABS_MT_SLOT        = 0x2f
	ABS_MT_TOOL_TYPE   = 0x37
	ABS_MT_TOOL_X      = 0x3c
	ABS_MT_TOOL_Y      = 0x3d
	ABS_MT_TOUCH_MAJOR = 0x30
	ABS_MT_TOUCH_MINOR = 0x31
	ABS_MT_TRACKING_ID = 0x39
	ABS_MT_WIDTH_MAJOR = 0x32
	ABS_MT_WIDTH_MINOR = 0x33
	ABS_PRESSURE       = 0x18
	ABS_RESERVED       = 0x2e
	ABS_RUDDER         = 0x07
	ABS_RX             = 0x03
	ABS_RY             = 0x04
	ABS_RZ             = 0x05
	ABS_THROTTLE       = 0x06
	ABS_TILT_X         = 0x1a
	ABS_TILT_Y         = 0x1b
	ABS_TOOL_WIDTH     = 0x1c
	ABS_VOLUME         = 0x20
	ABS_WHEEL          = 0x08
	ABS_X              = 0x00
	ABS_Y              = 0x01
	ABS_Z              = 0x02
)

var ABSName = map[EvCode]string{
	0:  "ABS_X",
	1:  "ABS_Y",
	2:  "ABS_Z",
	3:  "ABS_RX",
	4:  "ABS_RY",
	5:  "ABS_RZ",
	6:  "ABS_THROTTLE",
	7:  "ABS_RUDDER",
	8:  "ABS_WHEEL",
	9:  "ABS_GAS",
	10: "ABS_BRAKE",
	16: "ABS_HAT0X",
	17: "ABS_HAT0Y",
	18: "ABS_HAT1X",
	19: "ABS_HAT1Y",
	20: "ABS_HAT2X",
	21: "ABS_HAT2Y",
	22: "ABS_HAT3X",
	23: "ABS_HAT3Y",
	24: "ABS_PRESSURE",
	25: "ABS_DISTANCE",
	26: "ABS_TILT_X",
	27: "ABS_TILT_Y",
	28: "ABS_TOOL_WIDTH",
	32: "ABS_VOLUME",
	40: "ABS_MISC",
	46: "ABS_RESERVED",
	47: "ABS_MT_SLOT",
	48: "ABS_MT_TOUCH_MAJOR",
	49: "ABS_MT_TOUCH_MINOR",
	50: "ABS_MT_WIDTH_MAJOR",
	51: "ABS_MT_WIDTH_MINOR",
	52: "ABS_MT_ORIENTATION",
	53: "ABS_MT_POSITION_X",
	54: "ABS_MT_POSITION_Y",
	55: "ABS_MT_TOOL_TYPE",
	56: "ABS_MT_BLOB_ID",
	57: "ABS_MT_TRACKING_ID",
	58: "ABS_MT_PRESSURE",
	59: "ABS_MT_DISTANCE",
	60: "ABS_MT_TOOL_X",
	61: "ABS_MT_TOOL_Y",
}

// BTN
const (
	BTN_0               = 0x100
	BTN_1               = 0x101
	BTN_2               = 0x102
	BTN_3               = 0x103
	BTN_4               = 0x104
	BTN_5               = 0x105
	BTN_6               = 0x106
	BTN_7               = 0x107
	BTN_8               = 0x108
	BTN_9               = 0x109
	BTN_A               = BTN_SOUTH
	BTN_B               = BTN_EAST
	BTN_BACK            = 0x116
	BTN_BASE            = 0x126
	BTN_BASE2           = 0x127
	BTN_BASE3           = 0x128
	BTN_BASE4           = 0x129
	BTN_BASE5           = 0x12a
	BTN_BASE6           = 0x12b
	BTN_C               = 0x132
	BTN_DEAD            = 0x12f
	BTN_DIGI            = 0x140
	BTN_DPAD_DOWN       = 0x221
	BTN_DPAD_LEFT       = 0x222
	BTN_DPAD_RIGHT      = 0x223
	BTN_DPAD_UP         = 0x220
	BTN_EAST            = 0x131
	BTN_EXTRA           = 0x114
	BTN_FORWARD         = 0x115
	BTN_GAMEPAD         = 0x130
	BTN_GEAR_DOWN       = 0x150
	BTN_GEAR_UP         = 0x151
	BTN_JOYSTICK        = 0x120
	BTN_LEFT            = 0x110
	BTN_MIDDLE          = 0x112
	BTN_MISC            = 0x100
	BTN_MODE            = 0x13c
	BTN_MOUSE           = 0x110
	BTN_NORTH           = 0x133
	BTN_PINKIE          = 0x125
	BTN_RIGHT           = 0x111
	BTN_SELECT          = 0x13a
	BTN_SIDE            = 0x113
	BTN_SOUTH           = 0x130
	BTN_START           = 0x13b
	BTN_STYLUS          = 0x14b
	BTN_STYLUS2         = 0x14c
	BTN_STYLUS3         = 0x149
	BTN_TASK            = 0x117
	BTN_THUMB           = 0x121
	BTN_THUMB2          = 0x122
	BTN_THUMBL          = 0x13d
	BTN_THUMBR          = 0x13e
	BTN_TL              = 0x136
	BTN_TL2             = 0x138
	BTN_TOOL_AIRBRUSH   = 0x144
	BTN_TOOL_BRUSH      = 0x142
	BTN_TOOL_DOUBLETAP  = 0x14d
	BTN_TOOL_FINGER     = 0x145
	BTN_TOOL_LENS       = 0x147
	BTN_TOOL_MOUSE      = 0x146
	BTN_TOOL_PEN        = 0x140
	BTN_TOOL_PENCIL     = 0x143
	BTN_TOOL_QUADTAP    = 0x14f
	BTN_TOOL_QUINTTAP   = 0x148
	BTN_TOOL_RUBBER     = 0x141
	BTN_TOOL_TRIPLETAP  = 0x14e
	BTN_TOP             = 0x123
	BTN_TOP2            = 0x124
	BTN_TOUCH           = 0x14a
	BTN_TR              = 0x137
	BTN_TR2             = 0x139
	BTN_TRIGGER         = 0x120
	BTN_TRIGGER_HAPPY   = 0x2c0
	BTN_TRIGGER_HAPPY1  = 0x2c0
	BTN_TRIGGER_HAPPY10 = 0x2c9
	BTN_TRIGGER_HAPPY11 = 0x2ca
	BTN_TRIGGER_HAPPY12 = 0x2cb
	BTN_TRIGGER_HAPPY13 = 0x2cc
	BTN_TRIGGER_HAPPY14 = 0x2cd
	BTN_TRIGGER_HAPPY15 = 0x2ce
	BTN_TRIGGER_HAPPY16 = 0x2cf
	BTN_TRIGGER_HAPPY17 = 0x2d0
	BTN_TRIGGER_HAPPY18 = 0x2d1
	BTN_TRIGGER_HAPPY19 = 0x2d2
	BTN_TRIGGER_HAPPY2  = 0x2c1
	BTN_TRIGGER_HAPPY20 = 0x2d3
	BTN_TRIGGER_HAPPY21 = 0x2d4
	BTN_TRIGGER_HAPPY22 = 0x2d5
	BTN_TRIGGER_HAPPY23 = 0x2d6
	BTN_TRIGGER_HAPPY24 = 0x2d7
	BTN_TRIGGER_HAPPY25 = 0x2d8
	BTN_TRIGGER_HAPPY26 = 0x2d9
	BTN_TRIGGER_HAPPY27 = 0x2da
	BTN_TRIGGER_HAPPY28 = 0x2db
	BTN_TRIGGER_HAPPY29 = 0x2dc
	BTN_TRIGGER_HAPPY3  = 0x2c2
	BTN_TRIGGER_HAPPY30 = 0x2dd
	BTN_TRIGGER_HAPPY31 = 0x2de
	BTN_TRIGGER_HAPPY32 = 0x2df
	BTN_TRIGGER_HAPPY33 = 0x2e0
	BTN_TRIGGER_HAPPY34 = 0x2e1
	BTN_TRIGGER_HAPPY35 = 0x2e2
	BTN_TRIGGER_HAPPY36 = 0x2e3
	BTN_TRIGGER_HAPPY37 = 0x2e4
	BTN_TRIGGER_HAPPY38 = 0x2e5
	BTN_TRIGGER_HAPPY39 = 0x2e6
	BTN_TRIGGER_HAPPY4  = 0x2c3
	BTN_TRIGGER_HAPPY40 = 0x2e7
	BTN_TRIGGER_HAPPY5  = 0x2c4
	BTN_TRIGGER_HAPPY6  = 0x2c5
	BTN_TRIGGER_HAPPY7  = 0x2c6
	BTN_TRIGGER_HAPPY8  = 0x2c7
	BTN_TRIGGER_HAPPY9  = 0x2c8
	BTN_WEST            = 0x134
	BTN_WHEEL           = 0x150
	BTN_X               = BTN_NORTH
	BTN_Y               = BTN_WEST
	BTN_Z               = 0x135
)

var BTNName = map[EvCode]string{
	256: "BTN_0",
	257: "BTN_1",
	258: "BTN_2",
	259: "BTN_3",
	260: "BTN_4",
	261: "BTN_5",
	262: "BTN_6",
	263: "BTN_7",
	264: "BTN_8",
	265: "BTN_9",
	272: "BTN_MOUSE",
	273: "BTN_RIGHT",
	274: "BTN_MIDDLE",
	275: "BTN_SIDE",
	276: "BTN_EXTRA",
	277: "BTN_FORWARD",
	278: "BTN_BACK",
	279: "BTN_TASK",
	288: "BTN_JOYSTICK",
	289: "BTN_THUMB",
	290: "BTN_THUMB2",
	291: "BTN_TOP",
	292: "BTN_TOP2",
	293: "BTN_PINKIE",
	294: "BTN_BASE",
	295: "BTN_BASE2",
	296: "BTN_BASE3",
	297: "BTN_BASE4",
	298: "BTN_BASE5",
	299: "BTN_BASE6",
	303: "BTN_DEAD",
	304: "BTN_GAMEPAD",
	305: "BTN_EAST",
	306: "BTN_C",
	307: "BTN_NORTH",
	308: "BTN_WEST",
	309: "BTN_Z",
	310: "BTN_TL",
	311: "BTN_TR",
	312: "BTN_TL2",
	313: "BTN_TR2",
	314: "BTN_SELECT",
	315: "BTN_START",
	316: "BTN_MODE",
	317: "BTN_THUMBL",
	318: "BTN_THUMBR",
	320: "BTN_TOOL_PEN",
	321: "BTN_TOOL_RUBBER",
	322: "BTN_TOOL_BRUSH",
	323: "BTN_TOOL_PENCIL",
	324: "BTN_TOOL_AIRBRUSH",
	325: "BTN_TOOL_FINGER",
	326: "BTN_TOOL_MOUSE",
	327: "BTN_TOOL_LENS",
	328: "BTN_TOOL_QUINTTAP",
	329: "BTN_STYLUS3",
	330: "BTN_TOUCH",
	331: "BTN_STYLUS",
	332: "BTN_STYLUS2",
	333: "BTN_TOOL_DOUBLETAP",
	334: "BTN_TOOL_TRIPLETAP",
	335: "BTN_TOOL_QUADTAP",
	336: "BTN_GEAR_DOWN",
	337: "BTN_GEAR_UP",
	544: "BTN_DPAD_UP",
	545: "BTN_DPAD_DOWN",
	546: "BTN_DPAD_LEFT",
	547: "BTN_DPAD_RIGHT",
	704: "BTN_TRIGGER_HAPPY",
	705: "BTN_TRIGGER_HAPPY2",
	706: "BTN_TRIGGER_HAPPY3",
	707: "BTN_TRIGGER_HAPPY4",
	708: "BTN_TRIGGER_HAPPY5",
	709: "BTN_TRIGGER_HAPPY6",
	710: "BTN_TRIGGER_HAPPY7",
	711: "BTN_TRIGGER_HAPPY8",
	712: "BTN_TRIGGER_HAPPY9",
	713: "BTN_TRIGGER_HAPPY10",
	714: "BTN_TRIGGER_HAPPY11",
	715: "BTN_TRIGGER_HAPPY12",
	716: "BTN_TRIGGER_HAPPY13",
	717: "BTN_TRIGGER_HAPPY14",
	718: "BTN_TRIGGER_HAPPY15",
	719: "BTN_TRIGGER_HAPPY16",
	720: "BTN_TRIGGER_HAPPY17",
	721: "BTN_TRIGGER_HAPPY18",
	722: "BTN_TRIGGER_HAPPY19",
	723: "BTN_TRIGGER_HAPPY20",
	724: "BTN_TRIGGER_HAPPY21",
	725: "BTN_TRIGGER_HAPPY22",
	726: "BTN_TRIGGER_HAPPY23",
	727: "BTN_TRIGGER_HAPPY24",
	728: "BTN_TRIGGER_HAPPY25",
	729: "BTN_TRIGGER_HAPPY26",
	730: "BTN_TRIGGER_HAPPY27",
	731: "BTN_TRIGGER_HAPPY28",
	732: "BTN_TRIGGER_HAPPY29",
	733: "BTN_TRIGGER_HAPPY30",
	734: "BTN_TRIGGER_HAPPY31",
	735: "BTN_TRIGGER_HAPPY32",
	736: "BTN_TRIGGER_HAPPY33",
	737: "BTN_TRIGGER_HAPPY34",
	738: "BTN_TRIGGER_HAPPY35",
	739: "BTN_TRIGGER_HAPPY36",
	740: "BTN_TRIGGER_HAPPY37",
	741: "BTN_TRIGGER_HAPPY38",
	742: "BTN_TRIGGER_HAPPY39",
	743: "BTN_TRIGGER_HAPPY40",
}

// BUS
const (
	BUS_ADB         = 0x17
	BUS_AMIGA       = 0x16
	BUS_ATARI       = 0x1B
	BUS_BLUETOOTH   = 0x05
	BUS_CEC         = 0x1E
	BUS_GAMEPORT    = 0x14
	BUS_GSC         = 0x1A
	BUS_HIL         = 0x04
	BUS_HOST        = 0x19
	BUS_I2C         = 0x18
	BUS_I8042       = 0x11
	BUS_INTEL_ISHTP = 0x1F
	BUS_ISA         = 0x10
	BUS_ISAPNP      = 0x02
	BUS_PARPORT     = 0x15
	BUS_PCI         = 0x01
	BUS_RMI         = 0x1D
	BUS_RS232       = 0x13
	BUS_SPI         = 0x1C
	BUS_USB         = 0x03
	BUS_VIRTUAL     = 0x06
	BUS_XTKBD       = 0x12
)

var BUSName = map[EvCode]string{
	1:  "BUS_PCI",
	2:  "BUS_ISAPNP",
	3:  "BUS_USB",
	4:  "BUS_HIL",
	5:  "BUS_BLUETOOTH",
	6:  "BUS_VIRTUAL",
	16: "BUS_ISA",
	17: "BUS_I8042",
	18: "BUS_XTKBD",
	19: "BUS_RS232",
	20: "BUS_GAMEPORT",
	21: "BUS_PARPORT",
	22: "BUS_AMIGA",
	23: "BUS_ADB",
	24: "BUS_I2C",
	25: "BUS_HOST",
	26: "BUS_GSC",
	27: "BUS_ATARI",
	28: "BUS_SPI",
	29: "BUS_RMI",
	30: "BUS_CEC",
	31: "BUS_INTEL_ISHTP",
}

// EV
const (
	EV_ABS       = 0x03
	EV_CNT       = (EV_MAX + 1)
	EV_FF        = 0x15
	EV_FF_STATUS = 0x17
	EV_KEY       = 0x01
	EV_LED       = 0x11
	EV_MAX       = 0x1f
	EV_MSC       = 0x04
	EV_PWR       = 0x16
	EV_REL       = 0x02
	EV_REP       = 0x14
	EV_SND       = 0x12
	EV_SW        = 0x05
	EV_SYN       = 0x00
)

var EVName = map[EvType]string{
	0:  "EV_SYN",
	1:  "EV_KEY",
	2:  "EV_REL",
	3:  "EV_ABS",
	4:  "EV_MSC",
	5:  "EV_SW",
	17: "EV_LED",
	18: "EV_SND",
	20: "EV_REP",
	21: "EV_FF",
	22: "EV_PWR",
	23: "EV_FF_STATUS",
}

// FF
const (
	FF_AUTOCENTER     = 0x61
	FF_CNT            = (FF_MAX + 1)
	FF_CONSTANT       = 0x52
	FF_CUSTOM         = 0x5d
	FF_DAMPER         = 0x55
	FF_EFFECT_MAX     = FF_RAMP
	FF_EFFECT_MIN     = FF_RUMBLE
	FF_FRICTION       = 0x54
	FF_GAIN           = 0x60
	FF_INERTIA        = 0x56
	FF_MAX            = 0x7f
	FF_MAX_EFFECTS    = FF_GAIN
	FF_PERIODIC       = 0x51
	FF_RAMP           = 0x57
	FF_RUMBLE         = 0x50
	FF_SAW_DOWN       = 0x5c
	FF_SAW_UP         = 0x5b
	FF_SINE           = 0x5a
	FF_SPRING         = 0x53
	FF_SQUARE         = 0x58
	FF_STATUS_MAX     = 0x01
	FF_STATUS_PLAYING = 0x01
	FF_STATUS_STOPPED = 0x00
	FF_TRIANGLE       = 0x59
	FF_WAVEFORM_MAX   = FF_CUSTOM
	FF_WAVEFORM_MIN   = FF_SQUARE
)

var FFName = map[EvCode]string{
	0:  "FF_STATUS_STOPPED",
	1:  "FF_STATUS_MAX",
	80: "FF_RUMBLE",
	81: "FF_PERIODIC",
	82: "FF_CONSTANT",
	83: "FF_SPRING",
	84: "FF_FRICTION",
	85: "FF_DAMPER",
	86: "FF_INERTIA",
	87: "FF_RAMP",
	88: "FF_SQUARE",
	89: "FF_TRIANGLE",
	90: "FF_SINE",
	91: "FF_SAW_UP",
	92: "FF_SAW_DOWN",
	93: "FF_CUSTOM",
	96: "FF_GAIN",
	97: "FF_AUTOCENTER",
}

// ID
const (
	ID_BUS     = 0
	ID_PRODUCT = 2
	ID_VENDOR  = 1
)

var IDName = map[EvCode]string{
	0: "ID_BUS",
	1: "ID_VENDOR",
	2: "ID_PRODUCT",
}

// KEY
const (
	KEY_0                        = 11
	KEY_1                        = 2
	KEY_102ND                    = 86
	KEY_10CHANNELSDOWN           = 0x1b9
	KEY_10CHANNELSUP             = 0x1b8
	KEY_2                        = 3
	KEY_3                        = 4
	KEY_3D_MODE                  = 0x26f
	KEY_4                        = 5
	KEY_5                        = 6
	KEY_6                        = 7
	KEY_7                        = 8
	KEY_8                        = 9
	KEY_9                        = 10
	KEY_A                        = 30
	KEY_AB                       = 0x196
	KEY_ADDRESSBOOK              = 0x1ad
	KEY_AGAIN                    = 129
	KEY_ALS_TOGGLE               = 0x230
	KEY_ALTERASE                 = 222
	KEY_ANGLE                    = 0x173
	KEY_APOSTROPHE               = 40
	KEY_APPSELECT                = 0x244
	KEY_ARCHIVE                  = 0x169
	KEY_ASPECT_RATIO             = 0x177
	KEY_ASSISTANT                = 0x247
	KEY_ATTENDANT_OFF            = 0x21c
	KEY_ATTENDANT_ON             = 0x21b
	KEY_ATTENDANT_TOGGLE         = 0x21d
	KEY_AUDIO                    = 0x188
	KEY_AUDIO_DESC               = 0x26e
	KEY_AUX                      = 0x186
	KEY_B                        = 48
	KEY_BACK                     = 158
	KEY_BACKSLASH                = 43
	KEY_BACKSPACE                = 14
	KEY_BASSBOOST                = 209
	KEY_BATTERY                  = 236
	KEY_BLUE                     = 0x191
	KEY_BLUETOOTH                = 237
	KEY_BOOKMARKS                = 156
	KEY_BREAK                    = 0x19b
	KEY_BRIGHTNESSDOWN           = 224
	KEY_BRIGHTNESSUP             = 225
	KEY_BRIGHTNESS_AUTO          = 244
	KEY_BRIGHTNESS_CYCLE         = 243
	KEY_BRIGHTNESS_MAX           = 0x251
	KEY_BRIGHTNESS_MIN           = 0x250
	KEY_BRIGHTNESS_TOGGLE        = KEY_DISPLAYTOGGLE
	KEY_BRIGHTNESS_ZERO          = KEY_BRIGHTNESS_AUTO
	KEY_BRL_DOT1                 = 0x1f1
	KEY_BRL_DOT10                = 0x1fa
	KEY_BRL_DOT2                 = 0x1f2
	KEY_BRL_DOT3                 = 0x1f3
	KEY_BRL_DOT4                 = 0x1f4
	KEY_BRL_DOT5                 = 0x1f5
	KEY_BRL_DOT6                 = 0x1f6
	KEY_BRL_DOT7                 = 0x1f7
	KEY_BRL_DOT8                 = 0x1f8
	KEY_BRL_DOT9                 = 0x1f9
	KEY_BUTTONCONFIG             = 0x240
	KEY_C                        = 46
	KEY_CALC                     = 140
	KEY_CALENDAR                 = 0x18d
	KEY_CAMERA                   = 212
	KEY_CAMERA_DOWN              = 0x218
	KEY_CAMERA_FOCUS             = 0x210
	KEY_CAMERA_LEFT              = 0x219
	KEY_CAMERA_RIGHT             = 0x21a
	KEY_CAMERA_UP                = 0x217
	KEY_CAMERA_ZOOMIN            = 0x215
	KEY_CAMERA_ZOOMOUT           = 0x216
	KEY_CANCEL                   = 223
	KEY_CAPSLOCK                 = 58
	KEY_CD                       = 0x17f
	KEY_CHANNEL                  = 0x16b
	KEY_CHANNELDOWN              = 0x193
	KEY_CHANNELUP                = 0x192
	KEY_CHAT                     = 216
	KEY_CLEAR                    = 0x163
	KEY_CLOSE                    = 206
	KEY_CLOSECD                  = 160
	KEY_CNT                      = (KEY_MAX + 1)
	KEY_COFFEE                   = 152
	KEY_COMMA                    = 51
	KEY_COMPOSE                  = 127
	KEY_COMPUTER                 = 157
	KEY_CONFIG                   = 171
	KEY_CONNECT                  = 218
	KEY_CONTEXT_MENU             = 0x1b6
	KEY_CONTROLPANEL             = 0x243
	KEY_COPY                     = 133
	KEY_CUT                      = 137
	KEY_CYCLEWINDOWS             = 154
	KEY_D                        = 32
	KEY_DASHBOARD                = 204
	KEY_DATA                     = 0x277
	KEY_DATABASE                 = 0x1aa
	KEY_DELETE                   = 111
	KEY_DELETEFILE               = 146
	KEY_DEL_EOL                  = 0x1c0
	KEY_DEL_EOS                  = 0x1c1
	KEY_DEL_LINE                 = 0x1c3
	KEY_DIGITS                   = 0x19d
	KEY_DIRECTION                = KEY_ROTATE_DISPLAY
	KEY_DIRECTORY                = 0x18a
	KEY_DISPLAYTOGGLE            = 0x1af
	KEY_DISPLAY_OFF              = 245
	KEY_DOCUMENTS                = 235
	KEY_DOLLAR                   = 0x1b2
	KEY_DOT                      = 52
	KEY_DOWN                     = 108
	KEY_DVD                      = 0x185
	KEY_E                        = 18
	KEY_EDIT                     = 176
	KEY_EDITOR                   = 0x1a6
	KEY_EJECTCD                  = 161
	KEY_EJECTCLOSECD             = 162
	KEY_EMAIL                    = 215
	KEY_END                      = 107
	KEY_ENTER                    = 28
	KEY_EPG                      = 0x16d
	KEY_EQUAL                    = 13
	KEY_ESC                      = 1
	KEY_EURO                     = 0x1b3
	KEY_EXIT                     = 174
	KEY_F                        = 33
	KEY_F1                       = 59
	KEY_F10                      = 68
	KEY_F11                      = 87
	KEY_F12                      = 88
	KEY_F13                      = 183
	KEY_F14                      = 184
	KEY_F15                      = 185
	KEY_F16                      = 186
	KEY_F17                      = 187
	KEY_F18                      = 188
	KEY_F19                      = 189
	KEY_F2                       = 60
	KEY_F20                      = 190
	KEY_F21                      = 191
	KEY_F22                      = 192
	KEY_F23                      = 193
	KEY_F24                      = 194
	KEY_F3                       = 61
	KEY_F4                       = 62
	KEY_F5                       = 63
	KEY_F6                       = 64
	KEY_F7                       = 65
	KEY_F8                       = 66
	KEY_F9                       = 67
	KEY_FASTFORWARD              = 208
	KEY_FASTREVERSE              = 0x275
	KEY_FAVORITES                = 0x16c
	KEY_FILE                     = 144
	KEY_FINANCE                  = 219
	KEY_FIND                     = 136
	KEY_FIRST                    = 0x194
	KEY_FN                       = 0x1d0
	KEY_FN_1                     = 0x1de
	KEY_FN_2                     = 0x1df
	KEY_FN_B                     = 0x1e4
	KEY_FN_D                     = 0x1e0
	KEY_FN_E                     = 0x1e1
	KEY_FN_ESC                   = 0x1d1
	KEY_FN_F                     = 0x1e2
	KEY_FN_F1                    = 0x1d2
	KEY_FN_F10                   = 0x1db
	KEY_FN_F11                   = 0x1dc
	KEY_FN_F12                   = 0x1dd
	KEY_FN_F2                    = 0x1d3
	KEY_FN_F3                    = 0x1d4
	KEY_FN_F4                    = 0x1d5
	KEY_FN_F5                    = 0x1d6
	KEY_FN_F6                    = 0x1d7
	KEY_FN_F7                    = 0x1d8
	KEY_FN_F8                    = 0x1d9
	KEY_FN_F9                    = 0x1da
	KEY_FN_RIGHT_SHIFT           = 0x1e5
	KEY_FN_S                     = 0x1e3
	KEY_FORWARD                  = 159
	KEY_FORWARDMAIL              = 233
	KEY_FRAMEBACK                = 0x1b4
	KEY_FRAMEFORWARD             = 0x1b5
	KEY_FRONT                    = 132
	KEY_FULL_SCREEN              = 0x174
	KEY_G                        = 34
	KEY_GAMES                    = 0x1a1
	KEY_GOTO                     = 0x162
	KEY_GRAPHICSEDITOR           = 0x1a8
	KEY_GRAVE                    = 41
	KEY_GREEN                    = 0x18f
	KEY_H                        = 35
	KEY_HANGEUL                  = 122
	KEY_HANGUEL                  = KEY_HANGEUL
	KEY_HANGUP_PHONE             = 0x1be
	KEY_HANJA                    = 123
	KEY_HELP                     = 138
	KEY_HENKAN                   = 92
	KEY_HIRAGANA                 = 91
	KEY_HOME                     = 102
	KEY_HOMEPAGE                 = 172
	KEY_HP                       = 211
	KEY_I                        = 23
	KEY_IMAGES                   = 0x1ba
	KEY_INFO                     = 0x166
	KEY_INSERT                   = 110
	KEY_INS_LINE                 = 0x1c2
	KEY_ISO                      = 170
	KEY_J                        = 36
	KEY_JOURNAL                  = 0x242
	KEY_K                        = 37
	KEY_KATAKANA                 = 90
	KEY_KATAKANAHIRAGANA         = 93
	KEY_KBDILLUMDOWN             = 229
	KEY_KBDILLUMTOGGLE           = 228
	KEY_KBDILLUMUP               = 230
	KEY_KBDINPUTASSIST_ACCEPT    = 0x264
	KEY_KBDINPUTASSIST_CANCEL    = 0x265
	KEY_KBDINPUTASSIST_NEXT      = 0x261
	KEY_KBDINPUTASSIST_NEXTGROUP = 0x263
	KEY_KBDINPUTASSIST_PREV      = 0x260
	KEY_KBDINPUTASSIST_PREVGROUP = 0x262
	KEY_KBD_LAYOUT_NEXT          = 0x248
	KEY_KBD_LCD_MENU1            = 0x2b8
	KEY_KBD_LCD_MENU2            = 0x2b9
	KEY_KBD_LCD_MENU3            = 0x2ba
	KEY_KBD_LCD_MENU4            = 0x2bb
	KEY_KBD_LCD_MENU5            = 0x2bc
	KEY_KEYBOARD                 = 0x176
	KEY_KP0                      = 82
	KEY_KP1                      = 79
	KEY_KP2                      = 80
	KEY_KP3                      = 81
	KEY_KP4                      = 75
	KEY_KP5                      = 76
	KEY_KP6                      = 77
	KEY_KP7                      = 71
	KEY_KP8                      = 72
	KEY_KP9                      = 73
	KEY_KPASTERISK               = 55
	KEY_KPCOMMA                  = 121
	KEY_KPDOT                    = 83
	KEY_KPENTER                  = 96
	KEY_KPEQUAL                  = 117
	KEY_KPJPCOMMA                = 95
	KEY_KPLEFTPAREN              = 179
	KEY_KPMINUS                  = 74
	KEY_KPPLUS                   = 78
	KEY_KPPLUSMINUS              = 118
	KEY_KPRIGHTPAREN             = 180
	KEY_KPSLASH                  = 98
	KEY_L                        = 38
	KEY_LANGUAGE                 = 0x170
	KEY_LAST                     = 0x195
	KEY_LEFT                     = 105
	KEY_LEFTALT                  = 56
	KEY_LEFTBRACE                = 26
	KEY_LEFTCTRL                 = 29
	KEY_LEFTMETA                 = 125
	KEY_LEFTSHIFT                = 42
	KEY_LEFT_DOWN                = 0x269
	KEY_LEFT_UP                  = 0x268
	KEY_LIGHTS_TOGGLE            = 0x21e
	KEY_LINEFEED                 = 101
	KEY_LIST                     = 0x18b
	KEY_LOGOFF                   = 0x1b1
	KEY_M                        = 50
	KEY_MACRO                    = 112
	KEY_MACRO1                   = 0x290
	KEY_MACRO10                  = 0x299
	KEY_MACRO11                  = 0x29a
	KEY_MACRO12                  = 0x29b
	KEY_MACRO13                  = 0x29c
	KEY_MACRO14                  = 0x29d
	KEY_MACRO15                  = 0x29e
	KEY_MACRO16                  = 0x29f
	KEY_MACRO17                  = 0x2a0
	KEY_MACRO18                  = 0x2a1
	KEY_MACRO19                  = 0x2a2
	KEY_MACRO2                   = 0x291
	KEY_MACRO20                  = 0x2a3
	KEY_MACRO21                  = 0x2a4
	KEY_MACRO22                  = 0x2a5
	KEY_MACRO23                  = 0x2a6
	KEY_MACRO24                  = 0x2a7
	KEY_MACRO25                  = 0x2a8
	KEY_MACRO26                  = 0x2a9
	KEY_MACRO27                  = 0x2aa
	KEY_MACRO28                  = 0x2ab
	KEY_MACRO29                  = 0x2ac
	KEY_MACRO3                   = 0x292
	KEY_MACRO30                  = 0x2ad
	KEY_MACRO4                   = 0x293
	KEY_MACRO5                   = 0x294
	KEY_MACRO6                   = 0x295
	KEY_MACRO7                   = 0x296
	KEY_MACRO8                   = 0x297
	KEY_MACRO9                   = 0x298
	KEY_MACRO_PRESET1            = 0x2b3
	KEY_MACRO_PRESET2            = 0x2b4
	KEY_MACRO_PRESET3            = 0x2b5
	KEY_MACRO_PRESET_CYCLE       = 0x2b2
	KEY_MACRO_RECORD_START       = 0x2b0
	KEY_MACRO_RECORD_STOP        = 0x2b1
	KEY_MAIL                     = 155
	KEY_MAX                      = 0x2ff
	KEY_MEDIA                    = 226
	KEY_MEDIA_REPEAT             = 0x1b7
	KEY_MEDIA_TOP_MENU           = 0x26b
	KEY_MEMO                     = 0x18c
	KEY_MENU                     = 139
	KEY_MESSENGER                = 0x1ae
	KEY_MHP                      = 0x16f
	KEY_MICMUTE                  = 248
	KEY_MINUS                    = 12
	KEY_MIN_INTERESTING          = KEY_MUTE
	KEY_MODE                     = 0x175
	KEY_MOVE                     = 175
	KEY_MP3                      = 0x187
	KEY_MSDOS                    = 151
	KEY_MUHENKAN                 = 94
	KEY_MUTE                     = 113
	KEY_N                        = 49
	KEY_NEW                      = 181
	KEY_NEWS                     = 0x1ab
	KEY_NEXT                     = 0x197
	KEY_NEXTSONG                 = 163
	KEY_NEXT_FAVORITE            = 0x270
	KEY_NOTIFICATION_CENTER      = 0x1bc
	KEY_NUMERIC_0                = 0x200
	KEY_NUMERIC_1                = 0x201
	KEY_NUMERIC_11               = 0x26c
	KEY_NUMERIC_12               = 0x26d
	KEY_NUMERIC_2                = 0x202
	KEY_NUMERIC_3                = 0x203
	KEY_NUMERIC_4                = 0x204
	KEY_NUMERIC_5                = 0x205
	KEY_NUMERIC_6                = 0x206
	KEY_NUMERIC_7                = 0x207
	KEY_NUMERIC_8                = 0x208
	KEY_NUMERIC_9                = 0x209
	KEY_NUMERIC_A                = 0x20c
	KEY_NUMERIC_B                = 0x20d
	KEY_NUMERIC_C                = 0x20e
	KEY_NUMERIC_D                = 0x20f
	KEY_NUMERIC_POUND            = 0x20b
	KEY_NUMERIC_STAR             = 0x20a
	KEY_NUMLOCK                  = 69
	KEY_O                        = 24
	KEY_OK                       = 0x160
	KEY_ONSCREEN_KEYBOARD        = 0x278
	KEY_OPEN                     = 134
	KEY_OPTION                   = 0x165
	KEY_P                        = 25
	KEY_PAGEDOWN                 = 109
	KEY_PAGEUP                   = 104
	KEY_PASTE                    = 135
	KEY_PAUSE                    = 119
	KEY_PAUSECD                  = 201
	KEY_PAUSE_RECORD             = 0x272
	KEY_PC                       = 0x178
	KEY_PHONE                    = 169
	KEY_PICKUP_PHONE             = 0x1bd
	KEY_PLAY                     = 207
	KEY_PLAYCD                   = 200
	KEY_PLAYER                   = 0x183
	KEY_PLAYPAUSE                = 164
	KEY_POWER                    = 116
	KEY_POWER2                   = 0x164
	KEY_PRESENTATION             = 0x1a9
	KEY_PREVIOUS                 = 0x19c
	KEY_PREVIOUSSONG             = 165
	KEY_PRINT                    = 210
	KEY_PRIVACY_SCREEN_TOGGLE    = 0x279
	KEY_PROG1                    = 148
	KEY_PROG2                    = 149
	KEY_PROG3                    = 202
	KEY_PROG4                    = 203
	KEY_PROGRAM                  = 0x16a
	KEY_PROPS                    = 130
	KEY_PVR                      = 0x16e
	KEY_Q                        = 16
	KEY_QUESTION                 = 214
	KEY_R                        = 19
	KEY_RADIO                    = 0x181
	KEY_RECORD                   = 167
	KEY_RED                      = 0x18e
	KEY_REDO                     = 182
	KEY_REFRESH                  = 173
	KEY_REPLY                    = 232
	KEY_RESERVED                 = 0
	KEY_RESTART                  = 0x198
	KEY_REWIND                   = 168
	KEY_RFKILL                   = 247
	KEY_RIGHT                    = 106
	KEY_RIGHTALT                 = 100
	KEY_RIGHTBRACE               = 27
	KEY_RIGHTCTRL                = 97
	KEY_RIGHTMETA                = 126
	KEY_RIGHTSHIFT               = 54
	KEY_RIGHT_DOWN               = 0x267
	KEY_RIGHT_UP                 = 0x266
	KEY_RO                       = 89
	KEY_ROOT_MENU                = 0x26a
	KEY_ROTATE_DISPLAY           = 153
	KEY_ROTATE_LOCK_TOGGLE       = 0x231
	KEY_S                        = 31
	KEY_SAT                      = 0x17d
	KEY_SAT2                     = 0x17e
	KEY_SAVE                     = 234
	KEY_SCALE                    = 120
	KEY_SCREEN                   = KEY_ASPECT_RATIO
	KEY_SCREENLOCK               = KEY_COFFEE
	KEY_SCREENSAVER              = 0x245
	KEY_SCROLLDOWN               = 178
	KEY_SCROLLLOCK               = 70
	KEY_SCROLLUP                 = 177
	KEY_SEARCH                   = 217
	KEY_SELECT                   = 0x161
	KEY_SELECTIVE_SCREENSHOT     = 0x27a
	KEY_SEMICOLON                = 39
	KEY_SEND                     = 231
	KEY_SENDFILE                 = 145
	KEY_SETUP                    = 141
	KEY_SHOP                     = 221
	KEY_SHUFFLE                  = 0x19a
	KEY_SLASH                    = 53
	KEY_SLEEP                    = 142
	KEY_SLOW                     = 0x199
	KEY_SLOWREVERSE              = 0x276
	KEY_SOUND                    = 213
	KEY_SPACE                    = 57
	KEY_SPELLCHECK               = 0x1b0
	KEY_SPORT                    = 220
	KEY_SPREADSHEET              = 0x1a7
	KEY_STOP                     = 128
	KEY_STOPCD                   = 166
	KEY_STOP_RECORD              = 0x271
	KEY_SUBTITLE                 = 0x172
	KEY_SUSPEND                  = 205
	KEY_SWITCHVIDEOMODE          = 227
	KEY_SYSRQ                    = 99
	KEY_T                        = 20
	KEY_TAB                      = 15
	KEY_TAPE                     = 0x180
	KEY_TASKMANAGER              = 0x241
	KEY_TEEN                     = 0x19e
	KEY_TEXT                     = 0x184
	KEY_TIME                     = 0x167
	KEY_TITLE                    = 0x171
	KEY_TOUCHPAD_OFF             = 0x214
	KEY_TOUCHPAD_ON              = 0x213
	KEY_TOUCHPAD_TOGGLE          = 0x212
	KEY_TUNER                    = 0x182
	KEY_TV                       = 0x179
	KEY_TV2                      = 0x17a
	KEY_TWEN                     = 0x19f
	KEY_U                        = 22
	KEY_UNDO                     = 131
	KEY_UNKNOWN                  = 240
	KEY_UNMUTE                   = 0x274
	KEY_UP                       = 103
	KEY_UWB                      = 239
	KEY_V                        = 47
	KEY_VCR                      = 0x17b
	KEY_VCR2                     = 0x17c
	KEY_VENDOR                   = 0x168
	KEY_VIDEO                    = 0x189
	KEY_VIDEOPHONE               = 0x1a0
	KEY_VIDEO_NEXT               = 241
	KEY_VIDEO_PREV               = 242
	KEY_VOD                      = 0x273
	KEY_VOICECOMMAND             = 0x246
	KEY_VOICEMAIL                = 0x1ac
	KEY_VOLUMEDOWN               = 114
	KEY_VOLUMEUP                 = 115
	KEY_W                        = 17
	KEY_WAKEUP                   = 143
	KEY_WIMAX                    = KEY_WWAN
	KEY_WLAN                     = 238
	KEY_WORDPROCESSOR            = 0x1a5
	KEY_WPS_BUTTON               = 0x211
	KEY_WWAN                     = 246
	KEY_WWW                      = 150
	KEY_X                        = 45
	KEY_XFER                     = 147
	KEY_Y                        = 21
	KEY_YELLOW                   = 0x190
	KEY_YEN                      = 124
	KEY_Z                        = 44
	KEY_ZENKAKUHANKAKU           = 85
	KEY_ZOOM                     = KEY_FULL_SCREEN
	KEY_ZOOMIN                   = 0x1a2
	KEY_ZOOMOUT                  = 0x1a3
	KEY_ZOOMRESET                = 0x1a4
)

var KEYName = map[EvCode]string{
	0:   "KEY_RESERVED",
	1:   "KEY_ESC",
	2:   "KEY_1",
	3:   "KEY_2",
	4:   "KEY_3",
	5:   "KEY_4",
	6:   "KEY_5",
	7:   "KEY_6",
	8:   "KEY_7",
	9:   "KEY_8",
	10:  "KEY_9",
	11:  "KEY_0",
	12:  "KEY_MINUS",
	13:  "KEY_EQUAL",
	14:  "KEY_BACKSPACE",
	15:  "KEY_TAB",
	16:  "KEY_Q",
	17:  "KEY_W",
	18:  "KEY_E",
	19:  "KEY_R",
	20:  "KEY_T",
	21:  "KEY_Y",
	22:  "KEY_U",
	23:  "KEY_I",
	24:  "KEY_O",
	25:  "KEY_P",
	26:  "KEY_LEFTBRACE",
	27:  "KEY_RIGHTBRACE",
	28:  "KEY_ENTER",
	29:  "KEY_LEFTCTRL",
	30:  "KEY_A",
	31:  "KEY_S",
	32:  "KEY_D",
	33:  "KEY_F",
	34:  "KEY_G",
	35:  "KEY_H",
	36:  "KEY_J",
	37:  "KEY_K",
	38:  "KEY_L",
	39:  "KEY_SEMICOLON",
	40:  "KEY_APOSTROPHE",
	41:  "KEY_GRAVE",
	42:  "KEY_LEFTSHIFT",
	43:  "KEY_BACKSLASH",
	44:  "KEY_Z",
	45:  "KEY_X",
	46:  "KEY_C",
	47:  "KEY_V",
	48:  "KEY_B",
	49:  "KEY_N",
	50:  "KEY_M",
	51:  "KEY_COMMA",
	52:  "KEY_DOT",
	53:  "KEY_SLASH",
	54:  "KEY_RIGHTSHIFT",
	55:  "KEY_KPASTERISK",
	56:  "KEY_LEFTALT",
	57:  "KEY_SPACE",
	58:  "KEY_CAPSLOCK",
	59:  "KEY_F1",
	60:  "KEY_F2",
	61:  "KEY_F3",
	62:  "KEY_F4",
	63:  "KEY_F5",
	64:  "KEY_F6",
	65:  "KEY_F7",
	66:  "KEY_F8",
	67:  "KEY_F9",
	68:  "KEY_F10",
	69:  "KEY_NUMLOCK",
	70:  "KEY_SCROLLLOCK",
	71:  "KEY_KP7",
	72:  "KEY_KP8",
	73:  "KEY_KP9",
	74:  "KEY_KPMINUS",
	75:  "KEY_KP4",
	76:  "KEY_KP5",
	77:  "KEY_KP6",
	78:  "KEY_KPPLUS",
	79:  "KEY_KP1",
	80:  "KEY_KP2",
	81:  "KEY_KP3",
	82:  "KEY_KP0",
	83:  "KEY_KPDOT",
	85:  "KEY_ZENKAKUHANKAKU",
	86:  "KEY_102ND",
	87:  "KEY_F11",
	88:  "KEY_F12",
	89:  "KEY_RO",
	90:  "KEY_KATAKANA",
	91:  "KEY_HIRAGANA",
	92:  "KEY_HENKAN",
	93:  "KEY_KATAKANAHIRAGANA",
	94:  "KEY_MUHENKAN",
	95:  "KEY_KPJPCOMMA",
	96:  "KEY_KPENTER",
	97:  "KEY_RIGHTCTRL",
	98:  "KEY_KPSLASH",
	99:  "KEY_SYSRQ",
	100: "KEY_RIGHTALT",
	101: "KEY_LINEFEED",
	102: "KEY_HOME",
	103: "KEY_UP",
	104: "KEY_PAGEUP",
	105: "KEY_LEFT",
	106: "KEY_RIGHT",
	107: "KEY_END",
	108: "KEY_DOWN",
	109: "KEY_PAGEDOWN",
	110: "KEY_INSERT",
	111: "KEY_DELETE",
	112: "KEY_MACRO",
	113: "KEY_MUTE",
	114: "KEY_VOLUMEDOWN",
	115: "KEY_VOLUMEUP",
	116: "KEY_POWER",
	117: "KEY_KPEQUAL",
	118: "KEY_KPPLUSMINUS",
	119: "KEY_PAUSE",
	120: "KEY_SCALE",
	121: "KEY_KPCOMMA",
	122: "KEY_HANGEUL",
	123: "KEY_HANJA",
	124: "KEY_YEN",
	125: "KEY_LEFTMETA",
	126: "KEY_RIGHTMETA",
	127: "KEY_COMPOSE",
	128: "KEY_STOP",
	129: "KEY_AGAIN",
	130: "KEY_PROPS",
	131: "KEY_UNDO",
	132: "KEY_FRONT",
	133: "KEY_COPY",
	134: "KEY_OPEN",
	135: "KEY_PASTE",
	136: "KEY_FIND",
	137: "KEY_CUT",
	138: "KEY_HELP",
	139: "KEY_MENU",
	140: "KEY_CALC",
	141: "KEY_SETUP",
	142: "KEY_SLEEP",
	143: "KEY_WAKEUP",
	144: "KEY_FILE",
	145: "KEY_SENDFILE",
	146: "KEY_DELETEFILE",
	147: "KEY_XFER",
	148: "KEY_PROG1",
	149: "KEY_PROG2",
	150: "KEY_WWW",
	151: "KEY_MSDOS",
	152: "KEY_COFFEE",
	153: "KEY_ROTATE_DISPLAY",
	154: "KEY_CYCLEWINDOWS",
	155: "KEY_MAIL",
	156: "KEY_BOOKMARKS",
	157: "KEY_COMPUTER",
	158: "KEY_BACK",
	159: "KEY_FORWARD",
	160: "KEY_CLOSECD",
	161: "KEY_EJECTCD",
	162: "KEY_EJECTCLOSECD",
	163: "KEY_NEXTSONG",
	164: "KEY_PLAYPAUSE",
	165: "KEY_PREVIOUSSONG",
	166: "KEY_STOPCD",
	167: "KEY_RECORD",
	168: "KEY_REWIND",
	169: "KEY_PHONE",
	170: "KEY_ISO",
	171: "KEY_CONFIG",
	172: "KEY_HOMEPAGE",
	173: "KEY_REFRESH",
	174: "KEY_EXIT",
	175: "KEY_MOVE",
	176: "KEY_EDIT",
	177: "KEY_SCROLLUP",
	178: "KEY_SCROLLDOWN",
	179: "KEY_KPLEFTPAREN",
	180: "KEY_KPRIGHTPAREN",
	181: "KEY_NEW",
	182: "KEY_REDO",
	183: "KEY_F13",
	184: "KEY_F14",
	185: "KEY_F15",
	186: "KEY_F16",
	187: "KEY_F17",
	188: "KEY_F18",
	189: "KEY_F19",
	190: "KEY_F20",
	191: "KEY_F21",
	192: "KEY_F22",
	193: "KEY_F23",
	194: "KEY_F24",
	200: "KEY_PLAYCD",
	201: "KEY_PAUSECD",
	202: "KEY_PROG3",
	203: "KEY_PROG4",
	204: "KEY_DASHBOARD",
	205: "KEY_SUSPEND",
	206: "KEY_CLOSE",
	207: "KEY_PLAY",
	208: "KEY_FASTFORWARD",
	209: "KEY_BASSBOOST",
	210: "KEY_PRINT",
	211: "KEY_HP",
	212: "KEY_CAMERA",
	213: "KEY_SOUND",
	214: "KEY_QUESTION",
	215: "KEY_EMAIL",
	216: "KEY_CHAT",
	217: "KEY_SEARCH",
	218: "KEY_CONNECT",
	219: "KEY_FINANCE",
	220: "KEY_SPORT",
	221: "KEY_SHOP",
	222: "KEY_ALTERASE",
	223: "KEY_CANCEL",
	224: "KEY_BRIGHTNESSDOWN",
	225: "KEY_BRIGHTNESSUP",
	226: "KEY_MEDIA",
	227: "KEY_SWITCHVIDEOMODE",
	228: "KEY_KBDILLUMTOGGLE",
	229: "KEY_KBDILLUMDOWN",
	230: "KEY_KBDILLUMUP",
	231: "KEY_SEND",
	232: "KEY_REPLY",
	233: "KEY_FORWARDMAIL",
	234: "KEY_SAVE",
	235: "KEY_DOCUMENTS",
	236: "KEY_BATTERY",
	237: "KEY_BLUETOOTH",
	238: "KEY_WLAN",
	239: "KEY_UWB",
	240: "KEY_UNKNOWN",
	241: "KEY_VIDEO_NEXT",
	242: "KEY_VIDEO_PREV",
	243: "KEY_BRIGHTNESS_CYCLE",
	244: "KEY_BRIGHTNESS_AUTO",
	245: "KEY_DISPLAY_OFF",
	246: "KEY_WWAN",
	247: "KEY_RFKILL",
	248: "KEY_MICMUTE",
	352: "KEY_OK",
	353: "KEY_SELECT",
	354: "KEY_GOTO",
	355: "KEY_CLEAR",
	356: "KEY_POWER2",
	357: "KEY_OPTION",
	358: "KEY_INFO",
	359: "KEY_TIME",
	360: "KEY_VENDOR",
	361: "KEY_ARCHIVE",
	362: "KEY_PROGRAM",
	363: "KEY_CHANNEL",
	364: "KEY_FAVORITES",
	365: "KEY_EPG",
	366: "KEY_PVR",
	367: "KEY_MHP",
	368: "KEY_LANGUAGE",
	369: "KEY_TITLE",
	370: "KEY_SUBTITLE",
	371: "KEY_ANGLE",
	372: "KEY_FULL_SCREEN",
	373: "KEY_MODE",
	374: "KEY_KEYBOARD",
	375: "KEY_ASPECT_RATIO",
	376: "KEY_PC",
	377: "KEY_TV",
	378: "KEY_TV2",
	379: "KEY_VCR",
	380: "KEY_VCR2",
	381: "KEY_SAT",
	382: "KEY_SAT2",
	383: "KEY_CD",
	384: "KEY_TAPE",
	385: "KEY_RADIO",
	386: "KEY_TUNER",
	387: "KEY_PLAYER",
	388: "KEY_TEXT",
	389: "KEY_DVD",
	390: "KEY_AUX",
	391: "KEY_MP3",
	392: "KEY_AUDIO",
	393: "KEY_VIDEO",
	394: "KEY_DIRECTORY",
	395: "KEY_LIST",
	396: "KEY_MEMO",
	397: "KEY_CALENDAR",
	398: "KEY_RED",
	399: "KEY_GREEN",
	400: "KEY_YELLOW",
	401: "KEY_BLUE",
	402: "KEY_CHANNELUP",
	403: "KEY_CHANNELDOWN",
	404: "KEY_FIRST",
	405: "KEY_LAST",
	406: "KEY_AB",
	407: "KEY_NEXT",
	408: "KEY_RESTART",
	409: "KEY_SLOW",
	410: "KEY_SHUFFLE",
	411: "KEY_BREAK",
	412: "KEY_PREVIOUS",
	413: "KEY_DIGITS",
	414: "KEY_TEEN",
	415: "KEY_TWEN",
	416: "KEY_VIDEOPHONE",
	417: "KEY_GAMES",
	418: "KEY_ZOOMIN",
	419: "KEY_ZOOMOUT",
	420: "KEY_ZOOMRESET",
	421: "KEY_WORDPROCESSOR",
	422: "KEY_EDITOR",
	423: "KEY_SPREADSHEET",
	424: "KEY_GRAPHICSEDITOR",
	425: "KEY_PRESENTATION",
	426: "KEY_DATABASE",
	427: "KEY_NEWS",
	428: "KEY_VOICEMAIL",
	429: "KEY_ADDRESSBOOK",
	430: "KEY_MESSENGER",
	431: "KEY_DISPLAYTOGGLE",
	432: "KEY_SPELLCHECK",
	433: "KEY_LOGOFF",
	434: "KEY_DOLLAR",
	435: "KEY_EURO",
	436: "KEY_FRAMEBACK",
	437: "KEY_FRAMEFORWARD",
	438: "KEY_CONTEXT_MENU",
	439: "KEY_MEDIA_REPEAT",
	440: "KEY_10CHANNELSUP",
	441: "KEY_10CHANNELSDOWN",
	442: "KEY_IMAGES",
	444: "KEY_NOTIFICATION_CENTER",
	445: "KEY_PICKUP_PHONE",
	446: "KEY_HANGUP_PHONE",
	448: "KEY_DEL_EOL",
	449: "KEY_DEL_EOS",
	450: "KEY_INS_LINE",
	451: "KEY_DEL_LINE",
	464: "KEY_FN",
	465: "KEY_FN_ESC",
	466: "KEY_FN_F1",
	467: "KEY_FN_F2",
	468: "KEY_FN_F3",
	469: "KEY_FN_F4",
	470: "KEY_FN_F5",
	471: "KEY_FN_F6",
	472: "KEY_FN_F7",
	473: "KEY_FN_F8",
	474: "KEY_FN_F9",
	475: "KEY_FN_F10",
	476: "KEY_FN_F11",
	477: "KEY_FN_F12",
	478: "KEY_FN_1",
	479: "KEY_FN_2",
	480: "KEY_FN_D",
	481: "KEY_FN_E",
	482: "KEY_FN_F",
	483: "KEY_FN_S",
	484: "KEY_FN_B",
	485: "KEY_FN_RIGHT_SHIFT",
	497: "KEY_BRL_DOT1",
	498: "KEY_BRL_DOT2",
	499: "KEY_BRL_DOT3",
	500: "KEY_BRL_DOT4",
	501: "KEY_BRL_DOT5",
	502: "KEY_BRL_DOT6",
	503: "KEY_BRL_DOT7",
	504: "KEY_BRL_DOT8",
	505: "KEY_BRL_DOT9",
	506: "KEY_BRL_DOT10",
	512: "KEY_NUMERIC_0",
	513: "KEY_NUMERIC_1",
	514: "KEY_NUMERIC_2",
	515: "KEY_NUMERIC_3",
	516: "KEY_NUMERIC_4",
	517: "KEY_NUMERIC_5",
	518: "KEY_NUMERIC_6",
	519: "KEY_NUMERIC_7",
	520: "KEY_NUMERIC_8",
	521: "KEY_NUMERIC_9",
	522: "KEY_NUMERIC_STAR",
	523: "KEY_NUMERIC_POUND",
	524: "KEY_NUMERIC_A",
	525: "KEY_NUMERIC_B",
	526: "KEY_NUMERIC_C",
	527: "KEY_NUMERIC_D",
	528: "KEY_CAMERA_FOCUS",
	529: "KEY_WPS_BUTTON",
	530: "KEY_TOUCHPAD_TOGGLE",
	531: "KEY_TOUCHPAD_ON",
	532: "KEY_TOUCHPAD_OFF",
	533: "KEY_CAMERA_ZOOMIN",
	534: "KEY_CAMERA_ZOOMOUT",
	535: "KEY_CAMERA_UP",
	536: "KEY_CAMERA_DOWN",
	537: "KEY_CAMERA_LEFT",
	538: "KEY_CAMERA_RIGHT",
	539: "KEY_ATTENDANT_ON",
	540: "KEY_ATTENDANT_OFF",
	541: "KEY_ATTENDANT_TOGGLE",
	542: "KEY_LIGHTS_TOGGLE",
	560: "KEY_ALS_TOGGLE",
	561: "KEY_ROTATE_LOCK_TOGGLE",
	576: "KEY_BUTTONCONFIG",
	577: "KEY_TASKMANAGER",
	578: "KEY_JOURNAL",
	579: "KEY_CONTROLPANEL",
	580: "KEY_APPSELECT",
	581: "KEY_SCREENSAVER",
	582: "KEY_VOICECOMMAND",
	583: "KEY_ASSISTANT",
	584: "KEY_KBD_LAYOUT_NEXT",
	592: "KEY_BRIGHTNESS_MIN",
	593: "KEY_BRIGHTNESS_MAX",
	608: "KEY_KBDINPUTASSIST_PREV",
	609: "KEY_KBDINPUTASSIST_NEXT",
	610: "KEY_KBDINPUTASSIST_PREVGROUP",
	611: "KEY_KBDINPUTASSIST_NEXTGROUP",
	612: "KEY_KBDINPUTASSIST_ACCEPT",
	613: "KEY_KBDINPUTASSIST_CANCEL",
	614: "KEY_RIGHT_UP",
	615: "KEY_RIGHT_DOWN",
	616: "KEY_LEFT_UP",
	617: "KEY_LEFT_DOWN",
	618: "KEY_ROOT_MENU",
	619: "KEY_MEDIA_TOP_MENU",
	620: "KEY_NUMERIC_11",
	621: "KEY_NUMERIC_12",
	622: "KEY_AUDIO_DESC",
	623: "KEY_3D_MODE",
	624: "KEY_NEXT_FAVORITE",
	625: "KEY_STOP_RECORD",
	626: "KEY_PAUSE_RECORD",
	627: "KEY_VOD",
	628: "KEY_UNMUTE",
	629: "KEY_FASTREVERSE",
	630: "KEY_SLOWREVERSE",
	631: "KEY_DATA",
	632: "KEY_ONSCREEN_KEYBOARD",
	633: "KEY_PRIVACY_SCREEN_TOGGLE",
	634: "KEY_SELECTIVE_SCREENSHOT",
	656: "KEY_MACRO1",
	657: "KEY_MACRO2",
	658: "KEY_MACRO3",
	659: "KEY_MACRO4",
	660: "KEY_MACRO5",
	661: "KEY_MACRO6",
	662: "KEY_MACRO7",
	663: "KEY_MACRO8",
	664: "KEY_MACRO9",
	665: "KEY_MACRO10",
	666: "KEY_MACRO11",
	667: "KEY_MACRO12",
	668: "KEY_MACRO13",
	669: "KEY_MACRO14",
	670: "KEY_MACRO15",
	671: "KEY_MACRO16",
	672: "KEY_MACRO17",
	673: "KEY_MACRO18",
	674: "KEY_MACRO19",
	675: "KEY_MACRO20",
	676: "KEY_MACRO21",
	677: "KEY_MACRO22",
	678: "KEY_MACRO23",
	679: "KEY_MACRO24",
	680: "KEY_MACRO25",
	681: "KEY_MACRO26",
	682: "KEY_MACRO27",
	683: "KEY_MACRO28",
	684: "KEY_MACRO29",
	685: "KEY_MACRO30",
	688: "KEY_MACRO_RECORD_START",
	689: "KEY_MACRO_RECORD_STOP",
	690: "KEY_MACRO_PRESET_CYCLE",
	691: "KEY_MACRO_PRESET1",
	692: "KEY_MACRO_PRESET2",
	693: "KEY_MACRO_PRESET3",
	696: "KEY_KBD_LCD_MENU1",
	697: "KEY_KBD_LCD_MENU2",
	698: "KEY_KBD_LCD_MENU3",
	699: "KEY_KBD_LCD_MENU4",
	700: "KEY_KBD_LCD_MENU5",
}

// LED
const (
	LED_CAPSL    = 0x01
	LED_CHARGING = 0x0a
	LED_CNT      = (LED_MAX + 1)
	LED_COMPOSE  = 0x03
	LED_KANA     = 0x04
	LED_MAIL     = 0x09
	LED_MAX      = 0x0f
	LED_MISC     = 0x08
	LED_MUTE     = 0x07
	LED_NUML     = 0x00
	LED_SCROLLL  = 0x02
	LED_SLEEP    = 0x05
	LED_SUSPEND  = 0x06
)

var LEDName = map[EvCode]string{
	0:  "LED_NUML",
	1:  "LED_CAPSL",
	2:  "LED_SCROLLL",
	3:  "LED_COMPOSE",
	4:  "LED_KANA",
	5:  "LED_SLEEP",
	6:  "LED_SUSPEND",
	7:  "LED_MUTE",
	8:  "LED_MISC",
	9:  "LED_MAIL",
	10: "LED_CHARGING",
}

// MSC
const (
	MSC_CNT       = (MSC_MAX + 1)
	MSC_GESTURE   = 0x02
	MSC_MAX       = 0x07
	MSC_PULSELED  = 0x01
	MSC_RAW       = 0x03
	MSC_SCAN      = 0x04
	MSC_SERIAL    = 0x00
	MSC_TIMESTAMP = 0x05
)

var MSCName = map[EvCode]string{
	0: "MSC_SERIAL",
	1: "MSC_PULSELED",
	2: "MSC_GESTURE",
	3: "MSC_RAW",
	4: "MSC_SCAN",
	5: "MSC_TIMESTAMP",
}

// MT
const (
	MT_TOOL_DIAL   = 0x0a
	MT_TOOL_FINGER = 0x00
	MT_TOOL_MAX    = 0x0f
	MT_TOOL_PALM   = 0x02
	MT_TOOL_PEN    = 0x01
)

var MTName = map[EvCode]string{
	0:  "MT_TOOL_FINGER",
	1:  "MT_TOOL_PEN",
	2:  "MT_TOOL_PALM",
	10: "MT_TOOL_DIAL",
	15: "MT_TOOL_MAX",
}

// PROP
const (
	PROP_ACCELEROMETER = 0x06
	PROP_BUTTONPAD     = 0x02
	PROP_DIRECT        = 0x01
	PROP_INTER         = 0x00
	PROP_INTING_STICK  = 0x05
	PROP_MAX           = 0x1f
	PROP_SEMI_MT       = 0x03
	PROP_TOPBUTTONPAD  = 0x04
)

var PROPName = map[EvProp]string{
	0: "PROP_INTER",
	1: "PROP_DIRECT",
	2: "PROP_BUTTONPAD",
	3: "PROP_SEMI_MT",
	4: "PROP_TOPBUTTONPAD",
	5: "PROP_INTING_STICK",
	6: "PROP_ACCELEROMETER",
}

// REL
const (
	REL_CNT           = (REL_MAX + 1)
	REL_DIAL          = 0x07
	REL_HWHEEL        = 0x06
	REL_HWHEEL_HI_RES = 0x0c
	REL_MAX           = 0x0f
	REL_MISC          = 0x09
	REL_RESERVED      = 0x0a
	REL_RX            = 0x03
	REL_RY            = 0x04
	REL_RZ            = 0x05
	REL_WHEEL         = 0x08
	REL_WHEEL_HI_RES  = 0x0b
	REL_X             = 0x00
	REL_Y             = 0x01
	REL_Z             = 0x02
)

var RELName = map[EvCode]string{
	0:  "REL_X",
	1:  "REL_Y",
	2:  "REL_Z",
	3:  "REL_RX",
	4:  "REL_RY",
	5:  "REL_RZ",
	6:  "REL_HWHEEL",
	7:  "REL_DIAL",
	8:  "REL_WHEEL",
	9:  "REL_MISC",
	10: "REL_RESERVED",
	11: "REL_WHEEL_HI_RES",
	12: "REL_HWHEEL_HI_RES",
}

// REP
const (
	REP_CNT    = (REP_MAX + 1)
	REP_DELAY  = 0x00
	REP_MAX    = 0x01
	REP_PERIOD = 0x01
)

var REPName = map[EvCode]string{
	0: "REP_DELAY",
	1: "REP_PERIOD",
}

// SND
const (
	SND_BELL  = 0x01
	SND_CLICK = 0x00
	SND_CNT   = (SND_MAX + 1)
	SND_MAX   = 0x07
	SND_TONE  = 0x02
)

var SNDName = map[EvCode]string{
	0: "SND_CLICK",
	1: "SND_BELL",
	2: "SND_TONE",
}

// SW
const (
	SW_CAMERA_LENS_COVER    = 0x09
	SW_CNT                  = (SW_MAX + 1)
	SW_DOCK                 = 0x05
	SW_FRONT_PROXIMITY      = 0x0b
	SW_HEADPHONE_INSERT     = 0x02
	SW_JACK_PHYSICAL_INSERT = 0x07
	SW_KEYPAD_SLIDE         = 0x0a
	SW_LID                  = 0x00
	SW_LINEIN_INSERT        = 0x0d
	SW_LINEOUT_INSERT       = 0x06
	SW_MACHINE_COVER        = 0x10
	SW_MAX                  = 0x10
	SW_MICROPHONE_INSERT    = 0x04
	SW_MUTE_DEVICE          = 0x0e
	SW_PEN_INSERTED         = 0x0f
	SW_RADIO                = SW_RFKILL_ALL
	SW_RFKILL_ALL           = 0x03
	SW_ROTATE_LOCK          = 0x0c
	SW_TABLET_MODE          = 0x01
	SW_VIDEOOUT_INSERT      = 0x08
)

var SWName = map[EvCode]string{
	0:  "SW_LID",
	1:  "SW_TABLET_MODE",
	2:  "SW_HEADPHONE_INSERT",
	3:  "SW_RFKILL_ALL",
	4:  "SW_MICROPHONE_INSERT",
	5:  "SW_DOCK",
	6:  "SW_LINEOUT_INSERT",
	7:  "SW_JACK_PHYSICAL_INSERT",
	8:  "SW_VIDEOOUT_INSERT",
	9:  "SW_CAMERA_LENS_COVER",
	10: "SW_KEYPAD_SLIDE",
	11: "SW_FRONT_PROXIMITY",
	12: "SW_ROTATE_LOCK",
	13: "SW_LINEIN_INSERT",
	14: "SW_MUTE_DEVICE",
	15: "SW_PEN_INSERTED",
	16: "SW_MACHINE_COVER",
}

// SYN
const (
	SYN_CNT       = (SYN_MAX + 1)
	SYN_CONFIG    = 1
	SYN_DROPPED   = 3
	SYN_MAX       = 0xf
	SYN_MT_REPORT = 2
	SYN_REPORT    = 0
)

var SYNName = map[EvCode]string{
	0: "SYN_REPORT",
	1: "SYN_CONFIG",
	2: "SYN_MT_REPORT",
	3: "SYN_DROPPED",
}
