package kbext

import evdev "github.com/holoplot/go-evdev"

var (
	// LayoutQuertyEnUs LayoutID = "querty-en-US"

	quertyEnUs = map[evdev.EvCode]keymap{
		evdev.KEY_NUMERIC_STAR: {plain: "*", altgr: "*", shift: "*"},
		evdev.KEY_NUMERIC_3:    {plain: "3", altgr: "3", shift: "3"},
		evdev.KEY_NUMERIC_2:    {plain: "2", altgr: "2", shift: "2"},
		evdev.KEY_NUMERIC_5:    {plain: "5", altgr: "5", shift: "5"},
		evdev.KEY_NUMERIC_4:    {plain: "4", altgr: "4", shift: "4"},
		evdev.KEY_NUMERIC_7:    {plain: "7", altgr: "7", shift: "7"},
		evdev.KEY_NUMERIC_6:    {plain: "6", altgr: "6", shift: "6"},
		evdev.KEY_NUMERIC_9:    {plain: "9", altgr: "9", shift: "9"},
		evdev.KEY_NUMERIC_8:    {plain: "8", altgr: "8", shift: "8"},
		evdev.KEY_NUMERIC_1:    {plain: "1", altgr: "1", shift: "1"},
		evdev.KEY_NUMERIC_0:    {plain: "0", altgr: "0", shift: "0"},

		evdev.KEY_KP4: {plain: "4", altgr: "4", shift: "4"},
		evdev.KEY_KP5: {plain: "5", altgr: "5", shift: "5"},
		evdev.KEY_KP6: {plain: "6", altgr: "6", shift: "6"},
		evdev.KEY_KP7: {plain: "7", altgr: "7", shift: "7"},
		evdev.KEY_KP0: {plain: "0", altgr: "0", shift: "0"},
		evdev.KEY_KP1: {plain: "1", altgr: "1", shift: "1"},
		evdev.KEY_KP2: {plain: "2", altgr: "2", shift: "2"},
		evdev.KEY_KP3: {plain: "3", altgr: "3", shift: "3"},
		evdev.KEY_KP8: {plain: "8", altgr: "8", shift: "8"},
		evdev.KEY_KP9: {plain: "9", altgr: "9", shift: "9"},

		evdev.KEY_U: {plain: "u", altgr: "u", shift: "U"},
		evdev.KEY_W: {plain: "w", altgr: "w", shift: "W"},
		evdev.KEY_E: {plain: "e", altgr: "e", shift: "E"},
		evdev.KEY_D: {plain: "d", altgr: "d", shift: "D"},
		evdev.KEY_G: {plain: "g", altgr: "g", shift: "G"},
		evdev.KEY_F: {plain: "f", altgr: "f", shift: "F"},
		evdev.KEY_A: {plain: "a", altgr: "a", shift: "A"},
		evdev.KEY_C: {plain: "c", altgr: "c", shift: "C"},
		evdev.KEY_B: {plain: "b", altgr: "b", shift: "B"},
		evdev.KEY_M: {plain: "m", altgr: "m", shift: "M"},
		evdev.KEY_L: {plain: "l", altgr: "l", shift: "L"},
		evdev.KEY_O: {plain: "o", altgr: "o", shift: "O"},
		evdev.KEY_N: {plain: "n", altgr: "n", shift: "N"},
		evdev.KEY_I: {plain: "i", altgr: "i", shift: "I"},
		evdev.KEY_H: {plain: "h", altgr: "h", shift: "H"},
		evdev.KEY_K: {plain: "k", altgr: "k", shift: "K"},
		evdev.KEY_J: {plain: "j", altgr: "j", shift: "J"},
		evdev.KEY_Q: {plain: "q", altgr: "q", shift: "Q"},
		evdev.KEY_P: {plain: "p", altgr: "p", shift: "P"},
		evdev.KEY_S: {plain: "s", altgr: "s", shift: "S"},
		evdev.KEY_X: {plain: "x", altgr: "x", shift: "X"},
		evdev.KEY_Z: {plain: "z", altgr: "z", shift: "Z"},
		evdev.KEY_T: {plain: "t", altgr: "t", shift: "T"},
		evdev.KEY_V: {plain: "v", altgr: "v", shift: "V"},
		evdev.KEY_R: {plain: "r", altgr: "r", shift: "R"},
		evdev.KEY_Y: {plain: "y", altgr: "y", shift: "Y"},

		evdev.KEY_1: {plain: "1", altgr: "~", shift: "!"},
		evdev.KEY_2: {plain: "2", altgr: "2", shift: "@"},
		evdev.KEY_3: {plain: "3", altgr: "^", shift: "#"},
		evdev.KEY_4: {plain: "4", altgr: "4", shift: "$"},
		evdev.KEY_5: {plain: "5", altgr: "5", shift: "%"},
		evdev.KEY_6: {plain: "6", altgr: "6", shift: "^"},
		evdev.KEY_7: {plain: "7", altgr: "7", shift: "&"},
		evdev.KEY_8: {plain: "8", altgr: "8", shift: "*"},
		evdev.KEY_9: {plain: "9", altgr: "9", shift: "("},
		evdev.KEY_0: {plain: "0", altgr: "0", shift: ")"},

		evdev.KEY_BACKSLASH:  {plain: "\\", altgr: "\\", shift: "|"},
		evdev.KEY_TAB:        {plain: "\t", altgr: "\t", shift: "\t"},
		evdev.KEY_MINUS:      {plain: "-", altgr: "-", shift: "-"},
		evdev.KEY_SPACE:      {plain: " ", altgr: " ", shift: " "},
		evdev.KEY_GRAVE:      {plain: "`", altgr: "`", shift: "`"},
		evdev.KEY_LEFTBRACE:  {plain: "[", altgr: "[", shift: "["},
		evdev.KEY_RIGHTBRACE: {plain: "]", altgr: "]", shift: "]"},
		evdev.KEY_COMMA:      {plain: ",", altgr: ",", shift: ","},
		evdev.KEY_EQUAL:      {plain: "=", altgr: "=", shift: "="},
		evdev.KEY_SEMICOLON:  {plain: ";", altgr: ";", shift: ";"},
		evdev.KEY_APOSTROPHE: {plain: "'", altgr: "'", shift: "'"},
		evdev.KEY_DOT:        {plain: ".", altgr: ".", shift: "."},
		evdev.KEY_SLASH:      {plain: "/", altgr: "/", shift: "/"},
	}
)
